CREATE TABLE climbr_users_to_swipe (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES climbr_users(id) ON DELETE CASCADE,
    user_to_swipe_id INTEGER REFERENCES climbr_users(id) ON DELETE CASCADE
);