CREATE TABLE climbr_users_matched (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES climbr_users(id) ON DELETE CASCADE,
    user_matched_id INTEGER REFERENCES climbr_users(id) ON DELETE CASCADE
);